server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
mybatis:
  type-aliases-package: com.ljm.chat.pojo
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.ljm.chat.utils.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql
#  reasonable: true

# jdbc_config   datasource
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leliao-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: svse
# Hikari will use the above plus the following to setup connection pooling
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
#      等待连接池分配连接的最大时长（ms）,超过这个时长还没可用的连接则发生SQLException，默认30秒
      connection-timeout: 30000
#      最小连接数
      minimum-idle: 5
#      最大连接数
      maximum-pool-size: 15
#      开启自动提交
      auto-commit: true
#      一个连接idle状态的的最大时长（ms）,超时则被释放（retired），默认10分钟
      idle-timeout: 600000
#      连接池名字
      pool-name: DatebookHikariCP
#      一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms，
#  建议设置比数据库超时时长少60秒，参考MySQL wait_timeout参数（show variables like '%timeout%';） -->
      max-lifetime: 28740000
      connection-test-query: SELECT 1

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 80
    height: 80
  tracker-list:            #TrackerList参数,支持多个
    - 47.101.67.223:22122